tasks:
  build:
    description: "Build the plugin"
    command: "bunx --bun tsdown"
    inputs:
      - /packages/codemirror/src/**/*
      - src/**/*
      - tsconfig.json
      - tsdown.config.ts
    outputs:
      - dist
  dev:
    description: "Build the plugin"
    command: "bunx --bun tsdown --watch ./src --watch ../codemirror/src"
    inputs:
      - /packages/codemirror/src/**/*
      - src/**/*
      - tsconfig.json
      - tsdown.config.ts
    outputs:
      - dist
